### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by nikhilsingh050** [Yashwanthv21/amazon#5]
Can you tell me how do i deploy this webapp on my pc? Using django?

**Comment by Yashwanthv21** [comment]
The project has been updated with instructions to run the project. Please check and let me know if it doesn't work.

**Comment by thelonewolf050** [comment]
Thanks for the update brother. Its working except the scraping part. I dont know R. Can you give me a direction to work on to fix the scraping part? You must have a rough idea of whats wrong.
